name: kalabox
proxy:
  node:
    - kalabox.lndo.site:8080
excludes:
  - node_modules
services:
  node:
    type: node:14
    build:
      - yarn install
    command: "su - node -c 'cd /app && yarn dev'"
    port: 8080
tooling:
  node:
    service: node
  yarn:
    service: node
  mdl:
    service: node
    cmd: markdownlint
  vuepress:
    service: node
  test:
    service: node
    cmd: yarn run test
    description: Run tests
  lint:
    service: node
    cmd: yarn run lint
    description: Run linting
