language: node_js
node_js:
  - '6'
services:
  - docker

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install cgroup-bin curl
  - curl -fsSL -o /tmp/lando-latest.deb http://installer.kalabox.io/lando-latest-dev.deb
  - sudo dpkg -i /tmp/lando-latest.deb
  - lando version

script:
  - lando npm install
  - lando start
  - lando bower install
  - lando gulp build
  - lando gulp test
