https://www.{default}/:
  type: redirect
  to: https://{default}/
https://kalabox.me/:
  type: redirect
  to: https://{default}/
https://www.kalabox.me/:
  type: redirect
  to: https://{default}/
https://docs.{default}/:
  type: redirect
  to: https://{default}/
https://pantheon.{default}/:
  type: redirect
  to: https://{default}/
https://php.{default}/:
  type: redirect
  to: https://{default}/
https://support.{default}/:
  type: redirect
  to: https://{default}/
https://{default}/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: true
    default_ttl: 604800
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: kalabox:http
