https://www.{default}/:
  type: upstream
  redirects:
    expires: -1s
    paths: {}
  cache:
    enabled: false
    default_ttl: 0
    cookies:
    - '*'
    headers:
    - Accept
    - Accept-Language
  ssi:
    enabled: false
  upstream: kalabox:http
https://{default}/:
  type: redirect
  to: https://www.{default}/
